server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recovery_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: DEBUG
    jdbc: DEBUG
    com.zaxxer.hikari: DEBUG

