server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recovery?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/client/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

logging:
  level:
    org.mybatis: DEBUG
    jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
